### ISSUE TITLE
New release for py3 support

### ISSUE THREAD

**Issue by moorepants** [chrisdembia/yeadon#124]
@chrisdembia Can you make a new release and push to pypi now that py3 support is available?

**Comment by chrisdembia** [comment]
I'm a bit busy right now. Could be a week before I can do this.

**Comment by chrisdembia** [comment]
Is this urgent?

**Comment by moorepants** [comment]
I can work off the dev branch until you do. I'm working on some stuff for BMD 2016 and all these packages from a few years back are py3 compatible. Just trying to get them all up-to-date.

I can tag the release and push to conda. The only thing I don't have permission to do is push to pypi. Maybe pypi let's you give other users permissions?

**Comment by chrisdembia** [comment]
You are now an Onwer and a Maintaner of yeadon on pypi.

**Comment by moorepants** [comment]
Cool, thanks.

**Comment by moorepants** [comment]
This is done now. Chris, can you update read the docs? Or give me permission to do so.

**Comment by chrisdembia** [comment]
I have updated the docs (and also have given you permission to do so).

**Comment by moorepants** [comment]
Great, thanks!
